INSERT INTO songs VALUES (1, "Thick of It", "KSI", "Pop", "160");
INSERT INTO songs VALUES (2, "Pull Up", "KSI", "Hip/Hop", "190");
INSERT INTO songs VALUES (3, "Holiday", "KSI", "Pop", "195");
INSERT INTO songs VALUES (4, "Real Name", "KSI", "Hip/Hop", "170");
INSERT INTO songs VALUES (5, "Fe!n", "Travis Scott", "Hip/Hop", "195");
INSERT INTO songs VALUES (6, "Astrothunder", "Travis Scott", "Hip/Hop", "145");
INSERT INTO songs VALUES (7, "Till Further Notice", "Travic Scott", "Hip/Hop", "310");
INSERT INTO songs VALUES (8, "Butterfly Effect", "Travis Scott", "Hip/Hop", "210");
INSERT INTO songs VALUES (9, "Grenade", "Bruno Mars", "Pop", "225");
INSERT INTO songs VALUES (10, "Die with a Smile", "Bruno Mars", "Pop", "250");
INSERT INTO songs VALUES (11, "Locked out of Heaven", "Bruno Mars", "Pop", "235");
INSERT INTO songs VALUES (12, "That's What I Like", "Bruno Mars", "Pop", "210");
INSERT INTO songs VALUES (13, "IDGAF", "Drake", "Rap", "260");
INSERT INTO songs VALUES (14, "Rich Baby Daddy", "Drake", "Rap", "320");
INSERT INTO songs VALUES (15, "Fair Trade", "Drake", "Rap", "290");
INSERT INTO songs VALUES (16, "One Dance", "Drake", "Rap", "240");
INSERT INTO songs VALUES (17, "MOTTO", "NF", "Rap", "235");
INSERT INTO songs VALUES (18, "MISTAKE", "NF", "Rap", "215");
INSERT INTO songs VALUES (19, "Lie", "NF", "Hip/Hop", "270");
INSERT INTO songs VALUES (20, "The Search", "NF", "Hip/Hop", "290");
